definitions:
  request.GetUserListResponse:
    properties:
      list:
        description: 用户列表
        items:
          $ref: '#/definitions/system.SysUserPublic'
        type: array
      total:
        description: 数量
        type: integer
    type: object
  request.Login:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  request.LoginResponse:
    properties:
      token:
        description: 令牌
        type: string
      user:
        allOf:
        - $ref: '#/definitions/system.SysUserPublic'
        description: 用户信息
    type: object
  request.SearchUser:
    properties:
      avatar:
        description: 头像
        type: string
      createdAt:
        type: string
      enable:
        description: 账号是否启用(启用:1,不启用:-1)
        type: integer
      id:
        description: 主键ID
        type: integer
      keyWord:
        type: string
      nickname:
        description: 昵称
        type: string
      page:
        type: integer
      pageSize:
        type: integer
      phone:
        description: 手机号
        type: string
      updatedAt:
        type: string
      username:
        description: 用户名
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  system.Router:
    properties:
      children:
        description: 子路由
        items:
          $ref: '#/definitions/system.Router'
        type: array
      componentPath:
        description: 组件路径
        type: string
      hidden:
        description: 是否显示在菜单
        type: boolean
      icon:
        description: 菜单标识图
        type: string
      id:
        description: 主键ID
        type: integer
      name:
        description: 菜单名称
        type: string
      parentId:
        description: 父ID
        type: integer
      path:
        description: 前端路由访问路径
        type: string
      routerOrder:
        description: 路由排序,由小到大,如{1,2,3,4}
        type: integer
    type: object
  system.SysUserPublic:
    properties:
      avatar:
        description: 头像
        type: string
      createdAt:
        type: string
      enable:
        description: 账号是否启用(启用:1,不启用:-1)
        type: integer
      id:
        description: 主键ID
        type: integer
      nickname:
        description: 昵称
        type: string
      phone:
        description: 手机号
        type: string
      updatedAt:
        type: string
      username:
        description: 用户名
        type: string
    type: object
info:
  contact: {}
paths:
  /api/check:
    post:
      produces:
      - application/json
      responses:
        "20000":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/request.GetUserListResponse'
                msg:
                  type: string
              type: object
        "40000":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "50000":
          description: 内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: 检查是否登录
      tags:
      - UserApis
  /api/file:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 上传的文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "20000":
          description: 上传成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: string
                msg:
                  type: string
              type: object
        "40000":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "50000":
          description: 内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: 头像上传
      tags:
      - UserApis
  /api/login:
    post:
      parameters:
      - description: 用户账号,用户密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "20000":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/request.LoginResponse'
                msg:
                  type: string
              type: object
        "40000":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "50000":
          description: 内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: 用户登录
      tags:
      - BaseApis
  /api/user:
    delete:
      parameters:
      - description: 用户主键
        in: body
        name: id
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "20000":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "40000":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "50000":
          description: 内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: 根据ID删除用户
      tags:
      - UserApis
    get:
      produces:
      - application/json
      responses:
        "20000":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  items:
                    $ref: '#/definitions/system.Router'
                  type: array
                msg:
                  type: string
              type: object
        "40000":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "50000":
          description: 内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: 获取路由树
      tags:
      - UserApis
    patch:
      parameters:
      - description: 用户信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/system.SysUserPublic'
      produces:
      - application/json
      responses:
        "20000":
          description: 上传成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: string
                msg:
                  type: string
              type: object
        "40000":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "50000":
          description: 内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: 根据ID更新用户信息
      tags:
      - UserApis
  /api/user/:id:
    get:
      parameters:
      - description: 用户主键ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "20000":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/system.SysUserPublic'
                msg:
                  type: string
              type: object
        "40000":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "50000":
          description: 内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: 根据ID获取用户信息
      tags:
      - UserApis
    patch:
      produces:
      - application/json
      responses:
        "20000":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: string
                msg:
                  type: string
              type: object
        "40000":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "50000":
          description: 内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: 重置用户密码
      tags:
      - UserApis
  /api/users:
    post:
      parameters:
      - description: 页数和页码为必传,传用户信息表示条件查询
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SearchUser'
      produces:
      - application/json
      responses:
        "20000":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/request.GetUserListResponse'
                msg:
                  type: string
              type: object
        "40000":
          description: 请求错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
        "50000":
          description: 内部错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                code:
                  type: integer
                msg:
                  type: string
              type: object
      summary: 获取用户列表
      tags:
      - UserApis
swagger: "2.0"
