database:
  username: "postgres"
  dbname: "gra"
redis:
  password: ""
jwt:
  sign: "test123123test"
upload:
  path: "D:\\static\\images\\"
  getImagePath: "/static/images"
user:
  createUserPassword: "123456"
  resetPassword: "123456"
casbin:
  casbinConfig: "./configs/enforcer_model.conf"
system:
  apiPrefix: "/api"