database:
  username: "postgres"
  password: "123456"
  host: "127.0.0.1"
  port: "5432"
  dbname: "gra"
redis:
  addr: "localhost:6379"
  password: ""
jwt:
  sign: "test123123test"
upload:
  path: "D:\\static\\images"
  getImagePath: "/static/images"
user:
  createUserPassword: "123456"
  resetPassword: "123456"